### ISSUE TITLE
Cannot create filesystem for UEFI bootloader via user-data file

### ISSUE THREAD

**Issue by maworsham** [lefeck/ubuntu-autoinstall-generator-tools#3]
I am attempting to use the following for auto installation and it keeps saying that the UEFI bootloader ~ "autoinstall config did not create needed bootloader partition". What is it that I need to adjust to get the code working?

``
  storage:
    config:
    - { ptable: gpt, path: /dev/sda, wipe: superblock-recursive, preserve: false, grub_device: true, type: disk, id: disk-sda }
    - { type: partition, wipe: superblock, preserve: false, number: 1, device: disk-sda, flag: boot, size: 1074M, id: partition-0 }
    - { type: format, fstype: fat32, volume: partition-0, id: format-0 }
    - { type: mount, path: /boot/efi, device: format-0, id: mount-0 }
    - { type: disk, path: /dev/sdb, wipe: superblock, preserve: false, grub_device: false, id: disk-sdb }
    - { type: lvm_volgroup, name: vg00, devices: [disk-sdb], id: lvm_volgroup-0 }
    - { type: lvm_partition, volgroup: lvm_volgroup-0, name: lvroot, size: 500G, id: lvm_partition-0 }
    - { type: format, fstype: ext4, volume: lvm_partition-0, id: format-2 }
    - { type: mount, path: /, device: format-2, id: mount-2 }
    - { type: lvm_partition, volgroup: lvm_volgroup-0, name: lvvar, size: 50G, id: lvm_partition-1 }
    - { type: format, fstype: ext4, volume: lvm_partition-1, id: format-3 }
    - { type: mount, path: /var, device: format-3, id: mount-3 }
    - { type: lvm_partition, volgroup: lvm_volgroup-0, name: lvsnap, size: 50G, id: lvm_partition-2 }
    - { type: format, fstype: ext4, volume: lvm_partition-2, id: format-4 }
    - { type: mount, path: /snap, device: format-4, id: mount-4 }
``

**Comment by lefeck** [comment]
I would like to know if you have a virtual machine or a physical installation? You need to check the device type before installing, if the device type name is not /dev/sda/ it won't load.

**Comment by maworsham** [comment]
It's a physical server, Dell PowerEdge R630. Trying to get one server figured out for kickstarting/auto installing, then I was going to use a similar user-data for the other two servers just changing the bonded IP address.

**Comment by lefeck** [comment]
That's a good idea, good luck, and if you have any other questions, I'd be happy to answer them.

**Comment by lefeck** [comment]
> It's a physical server, Dell PowerEdge R630. Trying to get one server figured out for kickstarting/auto installing, then I was going to use a similar user-data for the other two servers just changing the bonded IP address.

If there are no further questions, I'll close the ticket.

**Comment by maworsham** [comment]
I actually  figured it out. I needed to do the following to my grub commands in the user-data:

  storage:
    grub:
      reorder_uefi: false
    bootloader: grub
    config:
    - { ptable: gpt, path: /dev/sda, wipe: superblock-recursive, preserve: false, type: disk, id: disk-sda }
    - { type: partition, number: 1, device: disk-sda, size: 512M, flag: boot, grub_device: true, id: partition-0 }
    - { type: format, fstype: fat32, volume: partition-0, id: format-0 }
    - { type: mount, path: /boot/efi, device: format-0, id: mount-0 }
