### ISSUE TITLE
runcmd-first-boot.sh intrducing strange characters on new machine

### ISSUE THREAD

**Issue by kenzon** [lefeck/ubuntu-autoinstall-generator-tools#4]
Hi,

I have a fresh install of Ubuntu 24.04.1 LTS. I'm attempting to run the script to create an auto-install iso of 24.04 LTS.

It almost works, but the use of "runcmd-first-boot.sh" does not with the -j option.
The file is nicely enclosed on the iso and also created on the new machine onto /opt/runcmd-first-boot.sh

But the execution at first run has a problem as can be seen here:

The file runcmd-first-boot.sh:

#!/bin/bash
mv /etc/netplan/50-cloud-init.yaml /etc/netplan/01-network-sandbox.yaml
touch /etc/cloud/cloud-init.disabled

Login to the new machine shows the problem:
$ ls /etc/netplan/
'01-network-sandbox.yaml'$'\r

$ ls /etc/cloud/
cloud-init.disabled
'cloud-init.disabled'$'\r

Do you have any suggestions how to solve this ?

**Comment by lefeck** [comment]
The file /etc/netplan/50-cloud-init.yaml for the Ubuntu 24.04 server (minimum configuration) contains the following, which tells you how to disable the cloud-init feature

```txt
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
```

You can refer to the link: [cloud-init disabled](https://gist.github.com/zoilomora/f862f76335f5f53644a1b8e55fe98320)

**Comment by kenzon** [comment]
Hi,
thank you for the advice regarding disable cloud-init. 👍

But my actual problem is that the commands in the "runcmd-first-boot.sh" file is not executed correctly at the first run,
there is somehow added additional strange characters like "'$'\r", looks like some regular expression things.
